"""add practice and journal prompt models

Revision ID: 83595024615d
Revises: 9b42d17e5f3a
Create Date: 2025-12-26 17:46:37.657434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83595024615d'
down_revision = '9b42d17e5f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkin_id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checkin_id'], ['user_checkins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkin_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('practice_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checkin_id'], ['user_checkins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_model_pkey'))
    )
    op.drop_table('practices')
    op.drop_table('journal_prompts')
    # ### end Alembic commands ###
