"""refactor: move journal_prompt to Practice model, remove JournalPrompt table

Revision ID: 8cdb106cac0c
Revises: 9b110fca6f93
Create Date: 2025-12-26 20:54:25.358236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8cdb106cac0c'
down_revision = '9b110fca6f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_prompts')
    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('journal_prompt', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.drop_column('journal_prompt')

    op.create_table('journal_prompts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('checkin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['checkin_id'], ['user_checkins.id'], name=op.f('journal_prompts_checkin_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('journal_prompts_pkey'))
    )
    # ### end Alembic commands ###
