"""add structured journal fields (intention, self-care, tomorrow's goal)

Revision ID: 96483d3456a8
Revises: 8cdb106cac0c
Create Date: 2025-12-26 21:20:08.507064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96483d3456a8'
down_revision = '8cdb106cac0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intention_for_day', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('self_care_today', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('goal_for_tomorrow', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_column('goal_for_tomorrow')
        batch_op.drop_column('self_care_today')
        batch_op.drop_column('intention_for_day')

    # ### end Alembic commands ###
