"""Sprint 4: Add time_of_day to CheckIn, create JournalEntry and PracticeFeedback models

Revision ID: 9b110fca6f93
Revises: ac508cdd8438
Create Date: 2025-12-26 20:13:19.035969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b110fca6f93'
down_revision = 'ac508cdd8438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checkin_id'], ['user_checkins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('helped', sa.Boolean(), nullable=True),
    sa.Column('pacing', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Add time_of_day column as nullable first
    with op.batch_alter_table('user_checkins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_of_day', sa.String(length=10), nullable=True))

    # Update existing records with a default value
    op.execute("UPDATE user_checkins SET time_of_day = 'Morning' WHERE time_of_day IS NULL")

    # Now make the column non-nullable
    with op.batch_alter_table('user_checkins', schema=None) as batch_op:
        batch_op.alter_column('time_of_day', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_checkins', schema=None) as batch_op:
        batch_op.drop_column('time_of_day')

    op.drop_table('practice_feedbacks')
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
