"""add audio file to practice model

Revision ID: ac508cdd8438
Revises: ce9e059f4c6c
Create Date: 2025-12-26 18:25:17.123221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac508cdd8438'
down_revision = 'ce9e059f4c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.drop_column('audio_file')

    # ### end Alembic commands ###
